export type CanonicalKey =
    | 'HOLEID' | 'XCOLLAR' | 'YCOLLAR' | 'ZCOLLAR' | 'ENDDEPTH' | 'PROJECTCODE'
    | 'AT' | 'AZIMUTH' | 'DIP' | 'FROM' | 'TO' | 'LITH' | 'SAMPLEID';

export const CANONICAL_HEADERS: Record<CanonicalKey, string[]> = {
    HOLEID: [
        'HOLEID', 'HOLE_ID', 'HOLE ID', 'BHID', 'BH_ID', 'DRILLHOLE', 'DRILLHOLEID',
        'WELLID', 'WELL_ID', 'KUYUADI', 'KUYUID', 'KUYU_ADI', 'KUYU_ID', 'SONDAJ', 'SONDAJNO', 'SONDAJ_NO',
        'BORENO', 'BORE_NO', 'WELLNAME', 'WELL_NAME', 'HOLENAME', 'HOLE_NAME', 'DH_ID', 'DHID', 'ID', 'NAME'
    ],
    XCOLLAR: [
        'XCOLLAR', 'X', 'EAST', 'EASTING', 'UTMX', 'XUTM', 'XCOORD', 'XCOORDINATE', 'DOGU', 'DOGU_KOORD',
        'X_COLLAR', 'COLLAR_X', 'E', 'EAST_COORD', 'EASTING_M', 'X_COORD', 'X_COORDINATE', 'UTM_X',
        'DOGUKOORDINAT', 'DOGU_KOORDINAT', 'KOORDINAT_X', 'KOORD_X'
    ],
    YCOLLAR: [
        'YCOLLAR', 'Y', 'NORTH', 'NORTHING', 'UTMY', 'YUTM', 'YCOORD', 'YCOORDINATE', 'KUZEY', 'KUZEY_KOORD',
        'Y_COLLAR', 'COLLAR_Y', 'N', 'NORTH_COORD', 'NORTHING_M', 'Y_COORD', 'Y_COORDINATE', 'UTM_Y',
        'KUZEYKOORDINAT', 'KUZEY_KOORDINAT', 'KOORDINAT_Y', 'KOORD_Y'
    ],
    ZCOLLAR: [
        'ZCOLLAR', 'Z', 'RL', 'ELEV', 'ELEVATION', 'ZCOORD', 'Z_COLLAR', 'COLLAR_Z', 'KOT', 'YUKSEKLIK',
        'RAKIM', 'ALT', 'ALTITUDE', 'HEIGHT', 'SURFACE_RL', 'SURFACERL', 'COLLAR_RL', 'COLLARRL', 'Z_COORD',
        'KOTDEGERI', 'KOT_DEGERI', 'RAKIMDEGERI', 'YUKSEKLIKDEGERI'
    ],
    ENDDEPTH: [
        'ENDDEPTH', 'TOTAL_DEPTH', 'TD', 'MAX_DEPTH', 'EOH', 'TOTALDEPTH', 'DEPTH', 'SONDAJDERINLIK',
        'SONDAJ_DEPTH', 'END_DEPTH', 'FINALD_DEPTH', 'HOLE_DEPTH', 'HOLEDEPTH', 'DERINLIK', 'TOPLAMDERINLIK',
        'TOPLAM_DERINLIK', 'BITIS_DERINLIK', 'BITISDERINLIK', 'SON_DERINLIK', 'SONDERINLIK', 'EOD', 'ENDOFHOLE', 'END_OF_HOLE'
    ],
    AT: ['AT', 'DEPTH', 'MD', 'MEASURED_DEPTH', 'SURVEY_DEPTH', 'METRE', 'DOWNHOLE', 'OLCUM_DERINLIK', 'M_DEPTH'],
    AZIMUTH: ['AZIMUTH', 'AZI', 'BRG', 'BEARING', 'DIRECTION', 'YON', 'ISTIKAMET', 'AZ', 'AZIM', 'AZMUT', 'AZIMUT', 'COMPASS', 'HEADING', 'DIR', 'YON_ACISI', 'YONACISI', 'PUSULAYONU', 'PUSULA_YONU'],
    DIP: ['DIP', 'INCLINATION', 'INC', 'ANGLE', 'EGIM', 'DIPANGLE', 'INCL', 'DIP_ANGLE', 'INCLANGLE', 'INCL_ANGLE', 'TILT', 'SLOPE', 'EGIMACISI', 'EGIM_ACISI', 'DALIM', 'DALIMACISI', 'DALIM_ACISI'],
    FROM: ['FROM', 'FROM_M', 'FROM_DEPTH', 'DEPTH_FROM', 'START', 'BASLANGIC', 'BASLANGIC_DERINLIK', 'UST', 'USTDERINLIK', 'FROMDEPTH', 'STARTDEPTH'],
    TO: ['TO', 'TO_M', 'TO_DEPTH', 'DEPTH_TO', 'END', 'BITIS', 'BITIS_DERINLIK', 'ALT', 'ALTDERINLIK', 'SON', 'TODEPTH', 'FINISH'],
    LITH: ['LITH', 'LITHOLOGY', 'LITHCODE', 'ROCK_TYPE', 'ROCK', 'CODE', 'LITOLOJI', 'FORMASYON', 'BIRIM', 'KAYA', 'KOD', 'LITOLOJIKOD', 'LITOLOJI_KOD', 'KAYATURU', 'KAYA_TURU', 'FORMATION', 'UNIT', 'GEOLCODE', 'GEOL_CODE', 'DESCRIPTION', 'DESC'],
    SAMPLEID: ['SAMPLEID', 'SAMPLE_ID', 'SAMPLE', 'ID', 'SAMP_ID', 'SAMPNO', 'NUMUNEID', 'NUMUNE', 'SAMPID', 'SAMPLENO', 'SAMPLE_NO', 'NUMUNEADI', 'NUMUNE_ADI', 'NUMUNENO', 'NUMUNE_NO', 'SPECIMENID', 'SPECIMEN_ID'],
    PROJECTCODE: ['PROJECTCODE', 'PROJECT_ID', 'PROJECT', 'PROJE', 'PROJE_KODU', 'PROJEKODU']
};

export const GRADE_PATTERNS = [
    '_ppm', '_ppb', '_%', '_pct', '_grade', '_tenor',
    'Au', 'Ag', 'Cu', 'Pb', 'Zn', 'Fe', 'Ni', 'Co', 'Mo', 'As', 'Sb', 'Bi'
];
